language: php

dist: trusty

matrix:
  include:
  - php: 7.3
    env: ANALYSIS='true'
  - php: nightly

  allow_failures:
  - php: nightly

before_script:
- composer install -n

script:
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi

after_success:
- if [[ "$ANALYSIS" == 'true' ]]; then bash <(curl -s https://codecov.io/bash) ; fi